name: "blazeface"
backend: "onnxruntime"
max_batch_size : 256
input [
    {
        name:"input"
        data_type: TYPE_FP32
        dims: [3,640,640]
    }
]

output [
    {
        name: "boxes"
        data_type: TYPE_FP32
        dims: [22400,4]
    }
]
output [
    {
        name: "scores"
        data_type: TYPE_FP32
        dims: [22400,2]
    }
]

output [
    {
        name: "landmark"
        data_type: TYPE_FP32
        dims: [22400,10]
    }
]

dynamic_batching { }